### ISSUE TITLE
Kodi on win7 crashes

### ISSUE THREAD

**Issue by yossisw** [kodi-pvr/pvr.vbox#102]
Hi,
On 3 different computers running Win7 and Kodi ver 15.1 or 15.2 using VBox Tv GateWay,  Kodi is crashing after something like half an hour.
I know that other users are experiencing this.
I will appreciate if you can simulate this.
I really like this plugin and i will like to continue using it.
Thank you so much for all you efforts creating this plugin.

Best Regards
Yossi

**Comment by Jalle19** [comment]
Do you have a crash log?

**Comment by yossisw** [comment]
sorry for the dumb question ... but can you tell me how to do it?

**Comment by Jalle19** [comment]
See http://kodi.wiki/view/Windows_FAQ#Userdata (Crash report)

**Comment by yossisw** [comment]
http://www.jumbomail.me/Downloads.aspx?sid=51334A556C34795563506B3D

Thanks

**Comment by yossisw** [comment]
Hi,
Any update?

**Comment by yossisw** [comment]
Hi Sam,
Do you have any answer for me?

**Comment by Jalle19** [comment]
No not yet, haven't had time to work on it. The log you posted is also not the crash log, can you check if you have any other related files there? If Kodi really crashes (i.e. the window closes) then you should at least have some kind of dump file lying around and usually a separate crash log too.

**Comment by yossisw** [comment]
this is the only log file i found in C:\Users\yyy\AppData\Roaming\Kodi
no crash log.

10x

**Comment by yossisw** [comment]
This time the a crash dump file is created 
http://www.jumbomail.co.il/Downloads.aspx?sid=597A6F496237386E5A45303D

10x

**Comment by Jalle19** [comment]
Thanks, I'll see if I can make any sense of it.

**Comment by yossisw** [comment]
Hi,
What does it means? can i do something with it?

**Comment by Jalle19** [comment]
Wait for Kodi 15.2, this change will be included there and hopefully it fixes this issue.

**Comment by yossisw** [comment]
is it included already in 15.2 RC2? 
i can test it

**Comment by Jalle19** [comment]
No not yet.
