### ISSUE TITLE
Addon crashing after enabling live tv on openelec 6.0.0

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#107]
Hi,

I've been trying to get this to work but the same thing keeps happening. After I configure the Addon (just set the IP) I go to enable TV in the Kodi settings and it starts to process channels and then Kodi restarts. The same thing happens each time I try to enable TV.

Happy to provide any logs etc. that are needed.

I'm running a shuttle XS35GTV2, and nvidia legacy build of openelec. The Addon version is 1.3.8.

Thanks,

Ross

**Comment by Jalle19** [comment]
Please provide a debug log and if possible the cradh log that is generated.

**Comment by phunkyfish** [comment]
Here you go:

OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit kodi.old.log
http://sprunge.us/LBYH
OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit
kodi_crashlog_20151109201321.log
http://sprunge.us/FHHL

**Comment by Jalle19** [comment]
I'm sorry I'm making you jump through hoops but the crash log is useless since the stable versions of OpenElec doesn't have gdb installed (which generates a trace of what the program did at the time of the crash). I asked around and got this:

```
12:33:09 < fritsch> negge: use a Milhouse build and reproduce
```

Do you think you could do that? Make sure you get the right one for your hardware.

**Comment by phunkyfish** [comment]
Afraid I don't know what a Milhouse build is?
If you can advise what it is I'm sure I can try it.
R.

Sent from Outlook

    _____________________________

**Comment by Jalle19** [comment]
http://milhouse.openelec.tv/builds/master/Nvidia_Legacy/

**Comment by phunkyfish** [comment]
That was easy, it's based on Jarvis but the issue is the same.

Here you go:

OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit kodi.old.log
http://sprunge.us/eQaT
OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit
kodi_crashlog_20151110203537.log
http://sprunge.us/EWPM

**Comment by Jalle19** [comment]
Very strange, can you try clearing your PVR database? Just remove the TVxx.db files from userdata/Database

**Comment by Jalle19** [comment]
Also what happens if you browse to http://192.168.1.23:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&ExternalIP=192.168.1.23&FromChIndex=FirstChannel&Method=GetXmltvChannelsList&Port=55555&ToChIndex=LastChannel

**Comment by phunkyfish** [comment]
Same problem if I clear the PVR DB. Output of the browser request attached
but looks ok.

**Comment by phunkyfish** [comment]
Any update for me?

**Comment by Jalle19** [comment]
I'm sorry but I don't know why it crashes at all. Check the forums to see if someone else can replicate your issue, maybe their logs will look different.

**Comment by phunkyfish** [comment]
Which forum?

One thing I did notice is that the plugin version is 1.3.8 on Openelec 6.0
but the latest plugin version is 1.3.9 could that be causing the problem?

R.

**Comment by Jalle19** [comment]
Yeah that's been reported as well, no one knows why it's not 1.3.9 (the source seems to indicate that 1.3.9 is what is being shipped).

I was referring to forum.kodi.tv. There is a subforum there for this addon.

**Comment by phunkyfish** [comment]
Cool, thanks. I'll try there.
R.

Sent from Outlook




On Tue, Nov 17, 2015 at 12:39 AM -0800, "Sam Stenvall" <notifications@github.com> wrote:












Yeah that's been reported as well, no one knows why it's not 1.3.9 (the source seems to indicate that 1.3.9 is what is being shipped).



I was referring to forum.kodi.tv. There is a subforum there for this addon.

**Comment by phunkyfish** [comment]
Tried this on Kodi 15.2 on OSX. Plugin version is 1.3.9 and exactly the
same problem. Is the crash output of any use to you to help diagnose?

R.

**Comment by Jalle19** [comment]
Please post it just in case.

**Comment by phunkyfish** [comment]
Here you go. Fingers crossed.

R.

**Comment by Jalle19** [comment]
Can't see any logs here?

**Comment by phunkyfish** [comment]
Sorry, that's the OS log I attached. Here's the kodi log with Debug enabled.

R.

**Comment by phunkyfish** [comment]
Here are the files loaded before the crash.

http://192.168.1.23:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&Method=QueryExternalMediaStatus

14:16:47 T:123145303453696   DEBUG: CurlFile::Open(0x111f9e550)
http://192.168.1.23:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&Method=QuerySystemTime&TimeFormat=XMLTV

14:16:47 T:123145303990272   DEBUG: CurlFile::Open(0x111f9e550)
http://192.168.1.23:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&ExternalIP=192.168.1.23&FromChIndex=FirstChannel&Method=GetXmltvChannelsList&Port=55555&ToChIndex=LastChannel

**Comment by phunkyfish** [comment]
If I send the channel list file I get from the last URL above can you parse them to see if there is an entry causing the crash?

**Comment by phunkyfish** [comment]
Here is the channel list file. I've also attached vboxXmltv.xml from IPTV links page on the  vbox to see if that helps.. Had to rename to .txt to upload.

[HttpControlApp-RN.txt](https://github.com/kodi-pvr/pvr.vbox/files/50196/HttpControlApp-RN.txt)
[vboxXmltv.txt](https://github.com/kodi-pvr/pvr.vbox/files/50197/vboxXmltv.txt)

**Comment by clancyian** [comment]
Hi phunkyfisk,
I had this same problem. Unselecting TG4 on the VBOX channel list fixed this for me.
Maybe there is some problem handing the Irish Language EPG ?

**Comment by phunkyfish** [comment]
Cool, I'll try this and see do I have any luck.
Thanks!

Get Outlook




On Tue, Apr 5, 2016 at 10:10 AM -0700, "clancyian" <notifications@github.com> wrote:












Hi phunkyfisk,

I had this same problem. Unselecting TG4 on the VBOX channel list fixed this for me.

Maybe there is some problem handing the Irish Language EPG ?

**Comment by Jalle19** [comment]
That could very well be, there was a similar issue in the past. Very hard to tell without a crash log though.

**Comment by phunkyfish** [comment]
I had uploaded a crash log previously.
R.

Get Outlook




On Tue, Apr 5, 2016 at 11:22 AM -0700, "Sam Stenvall" <notifications@github.com> wrote:












That could very well be, there was a similar issue in the past. Very hard to tell without a crash log though.

**Comment by phunkyfish** [comment]
I'm afraid removing TG4 didn't work. I also have the radio channels, maybe
the same issue exists with their program guides as TG4's. Who knows.

**Comment by Jalle19** [comment]
@phunkyfish I do not see it?

**Comment by phunkyfish** [comment]
Here you go:

OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit kodi.old.log
http://sprunge.us/eQaT
OpenELECSR:~/.kodi/temp # /usr/bin/pastebinit kodi_crashlog_20151110203537.
log
http://sprunge.us/EWPM

Was posted back on the 10th Nov 2015.

R.

**Comment by phunkyfish** [comment]
Can be closed. No longer ocurring on libreelec 8

**Comment by Jalle19** [comment]
Thanks for reporting back!
