### ISSUE TITLE
Start Watching a recording before it is finished enhancement request

### ISSUE THREAD

**Issue by tomskiABC** [kodi-pvr/pvr.vbox#124]
If I start to watch a recording that is not yet finished, it causes the vbox to stop recording. So for example if a program is 30 minutes long and I start watching the still running recording when it is 20 minutes through, my recording stops after 20 minutes.

It would be nice to be able to start watching before the recording is finished.

Thanks.

**Comment by Jalle19** [comment]
Do you know if the same thing happens if you play the recording in e.g. VLC using the URL from the VBox interface?

**Comment by tomskiABC** [comment]
Hello -thanks for the reply

I should have tried that first, it is the same in vlc. The vbox client reports as still recording but it isn't. I will try vbox support.

**Comment by Jalle19** [comment]
I think I remember something similar with in-progress recordings while I was developing the addon. Try the latest firmware version if you haven't already.

**Comment by tomskiABC** [comment]
Cheers

Vbox support said this feature has been requested before, and it is on their list of possible enhancements. they said it would move up the list the more people ask for it.

Your add in works very well thanks for making it. much better experience with addin + kodi than native vbox client.
