### ISSUE TITLE
Video not working Nexus 7

### ISSUE THREAD

**Issue by andrefed** [kodi-pvr/pvr.vbox#125]
No video in preview mode (audio OK). Going full screen shows bits of window frame, arrows, buttons etc repeated messily all over the screen and no streamed video content is visible. Any other video works OK in Kodi. After having played any other video, the messy content in live TV described above does not happen and a black screen is visible instead, audio works fine. All this happens only on Nexus 7, same setup works perfectly on Nexus 5

**Comment by Jalle19** [comment]
I suspect it is a generic issue with that platform, i.e. not specific to this addon. You should file a ticket on trac.kodi.tv.

**Comment by Jalle19** [comment]
Please try again with the latest version of Kodi.
