### ISSUE TITLE
Android - EPG off by minus 20 minutes

### ISSUE THREAD

**Issue by rav3ndk** [kodi-pvr/pvr.vbox#127]
I am currently facing a strange issue after finishing setting up my new VBox XTI 3352. When I use the VBox TV Gateway PVR Add-on, the EPG guide shows start- and end times that are off by minus 20 minutes - so programs supposed to start at 20.00 and end 20.30 shows start 19.40 and end 20.10.
- Time is correct in both Android and Kodi.
- When I use the VBox directly (iPad app or browser directly) the EPG data is correct.
- When I try to use the Kodi IPTV PVR Add-on the EPG data is correct. Not a solution to use IPTV Add-on as recording functionality is missing.

Seeing that IPTV Add-on is showing correct EPG times, it seems apparent that the issue is with the VBox PVR Add-on.

I am using:
VBox TV Gateway PVR Add-on v2.1.10
Kodi v16.1 (was using 16.0 but upgraded in attempt to fix this issue)

Help :-)

**Comment by Jalle19** [comment]
What have you set the timezone to in the VBox interface?

**Comment by rav3ndk** [comment]
It's configured to read from Live signal and it's set to correct GMT+2:00.

**Comment by Jalle19** [comment]
Is this still an issue with the latest version of Kodi?

**Comment by rav3ndk** [comment]
@Jalle19 - sorry can't test this as I don't have the VBox anymore. As far as I recall the solution for me was to create an offset in advancedsettings.xml on the Kodi box. But like I said, can't really check anymore - sorry.

**Comment by Jalle19** [comment]
Okay, that's too bad. I'll close this in the mean time then.
