### ISSUE TITLE
Convert Category to Genre

### ISSUE THREAD

**Issue by mriksman** [kodi-pvr/pvr.vbox#130]
Currently, no Genre is generated. The PVR.Stalker addon performs a map between Category and Genre as so (see https://github.com/kodi-pvr/pvr.stalker/blob/master/src/XMLTV.cpp);

```
           node3 = prog->categories->first;
            while (node3) {
                if (node3->data)
                    p.categories.push_back((const char *) node3->data);

                node3 = node3->next;
            }
```

The above is already performed in a similar manner in the VBox PVR code. However, the PVR.Stalker client then runs this 'mapping' function;

`p.extra.genreType = EPGGenreByCategory(p.categories);
`

It should be simple enough to add this to the code; I just don't have the technical know-how to do it. Once done, we would have nice colours for Genres.

**Comment by Jalle19** [comment]
https://github.com/kodi-pvr/pvr.vbox/pull/146

**Comment by mriksman** [comment]
I see some work has been done on this. 
But... How can this update be pushed to Kodi? I see PVR addons are binaries and need to be built for a specific platform. I am using Kodi on Android TV - and it seems you can't do this for Android?
Was hoping to have a simple solution to get the latest updates, but it doesn't seem as simple as 'Install from ZIP file' :/

**Comment by Jalle19** [comment]
It will come automatically as part of a Kodi update sooner or later.

**Comment by mriksman** [comment]
Excited to see Kodi v17 hit the Google Play store, and my TVs have updated. VBox PVR Client shows 3.6.7, so the category-genre mapping should be taking place. Indeed, I can see genres like 'Soap, Melodrama' and 'Antiques, Collectibles'.

But they aren't coloured like I was expecting them to be... Any idea why? Have you got genre colours working OK on your end?
