### ISSUE TITLE
Kodi Crashing loading exteral EPG on Libreelec 7.0.2 (Kodi Jarvis 16.1)

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#131]
Hi,

I just upgraded to Kodi 16.1 and wanted to try the plugin again so I could get recording working (currently using Simple IPTV plugin).

Unfortunately Kodi still crashes on loading the EPG. I have posted crash logs in the past to no avail on previous versions. Was wondering if I send you the EPG and output of the channel list could you check and see if you can find the issue. It must be some special character or something in the guide. If you can send me the command to pull the channel list happy to send the out on (or pastebin). The EPG itself is 10/12Mb so not sure what the best way of sending that would be.

Note that Kodi is restarting, not the underlying OS.

Thanks in advance.

Ross

**Comment by phunkyfish** [comment]
Can be closed. No longer happens on LibreElec 8

**Comment by Jalle19** [comment]
Thanks for reporting back!
