### ISSUE TITLE
Channel order not preserved on version

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#132]
Hi,

I've noticed that the Vbox channel order is not preserved by the addon. Guide order is by LCN in the addon even though the backend is selected to provide ordering.

Running Libreelec 7.0.2, Kodi 16.1 Jarvis.

Note that if using the SimpleIPTV addon order is preserved correctly.

Thanks,

Ross

**Comment by Jalle19** [comment]
You'll have to check the "Set channel number using backend order" option in the addon settings.

**Comment by phunkyfish** [comment]
I don't have that option in the Addon settings.

Was it a recent addition? Or is it located somewhere else.

R.

**Comment by Jalle19** [comment]
It was added many months ago, it should be under the EPG tab.

**Comment by phunkyfish** [comment]
I'm on Kodi Jarvis, plugin version 2.1.10. I assume it's a newer version than that?

Running libreelec so not so easy to update.

R.

**Comment by Jalle19** [comment]
The option is not available in the Jarvis version. I'll try to backport some recent changes this week and release a new version.

**Comment by phunkyfish** [comment]
No need. I'm happy to wait to upgrade. Wouldn't like to taking resources
from any cool new features you're plan ;)

R.
