### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.vbox#155]
@relipo can you tag a new relase (`3.6.0`) after you've merged #154 ? See https://github.com/kodi-pvr/pvr.vbox/commit/c966c5fd9834a652c48f028d0d1e7cc5f7bba001 for what is required apart from tagging the revision.

**Comment by relipo** [comment]
I could, but I do have one more thing to add here (for now), and that's the padding times for the recording. So I should probably do that first. OK?

**Comment by Jalle19** [comment]
Sure, as long as we have something in time for the final release of Kodi v17.
