### ISSUE TITLE
Create github release for 3.6.1

### ISSUE THREAD

**Issue by candrews** [kodi-pvr/pvr.vbox#179]
It looks like the latest release version is 3.6.1. Can you please create the release in github?

Releases make things a lot easier for distributions (in my case, Gentoo) to package the add-on.

I specifically ask because the last release, 3.5.0, has a bug preventing compilation: https://bugs.gentoo.org/show_bug.cgi?id=605242 That issues doesn't exist in 3.6.1, but I can't use that until you tag it.

Thanks!

**Comment by Jalle19** [comment]
I'll try to remember to tag every release tomorrow. Ping me again if I forget.

**Comment by candrews** [comment]
@Jalle19 ping

**Comment by Jalle19** [comment]
Tagged everything now, latest version for Jarvis is 3.6.6.

**Comment by Jalle19** [comment]
Oh yeah but you need to wait for https://github.com/kodi-pvr/pvr.vbox/pull/180/files (3.6.7) to be merged, otherwise the changelog will be empty after 3.6.0.

**Comment by Jalle19** [comment]
3.6.7 is tagged now
