### ISSUE TITLE
Addon Error on Startup Libreelec 7.95.3 Beta - Kodi 17

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#182]
I get this error dialog on Kodi after installing and configuring the addon. 

"PVR clients: VBox TV Gateway PVR Client
Addon couldn't be loaded.

An unknown error has ocurred"

If I check the log I see this:

.517 T:546886906080   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
.517 T:546886906080   ERROR: CCurlFile::Open failed with code 0 for http://192.168.1.91:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&Method=QuerySwVersion|connection-timeout=3
.518 T:546886906080   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
.518 T:546886906080   ERROR: CCurlFile::Open failed with code 0 for http://192.168.1.91:80/cgi-bin/HttpControl/HttpControlApp?OPTION=1&Method=QuerySwVersion
.518 T:546886906080   ERROR: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Request failed: Unable to perform request (QuerySwVersion)
.518 T:546886906080   ERROR: ADDON: Dll VBox TV Gateway PVR Client - Client returned bad status (1) from Create and is not usable
.620 T:546878517472   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
.620 T:546878517472   ERROR: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5
.620 T:546878517472   ERROR: Open - failed to open source <https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5>
.620 T:546878517472   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5'
.728 T:546878517472   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
.728 T:546878517472   ERROR: CCurlFile::Open failed with code 0 for http://addons.libreelec.tv/8.1/WeTek_Hub/aarch64/addons.xml.gz.md5
.729 T:546878517472   ERROR: Open - failed to open source <http://addons.libreelec.tv/8.1/WeTek_Hub/aarch64/addons.xml.gz.md5>
.729 T:546878517472   ERROR: CRepository: failed read 'http://addons.libreelec.tv/8.1/WeTek_Hub/aarch64/addons.xml.gz.md5'

If I manually disable and enable the addon after boot it runs just fine.

Any ideas?

Regards,

Ross

**Comment by Jalle19** [comment]
Try enabling the "Wait for network" option in LibreElec's settings.

**Comment by phunkyfish** [comment]
Yes, I tried this but it didn't make a difference unfortunately.

R.

**Comment by phunkyfish** [comment]
This is what I enabled: http://kodi.wiki/view/Wake_on_lan

Do you mean something else?

R.

**Comment by Jalle19** [comment]
Yes, find the LibreElec settings, go to Network or Connections or whatever it's called, then enable "Wait for network".

**Comment by phunkyfish** [comment]
Ok, cool. I'll try that this evening and revert back.

R.

**Comment by phunkyfish** [comment]
Worked perfectly, thank you ;)

**Comment by Jalle19** [comment]
Great, thanks for reporting back!
