### ISSUE TITLE
Libreelec 8.0.0 Guide Empty after 24 hours

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#185]
On plugin version: 3.6.7.1

After 24 hours (I've only checked once each day) the guide will be empty. I'm not using external XMLTV just one loaded straight from the VBox (as it can not load an external XMTV itself).

Disable/Enable the plugin or rebooting libreelec will reload the guide.

The issue did not exist in any of the betas prior to 8.0.0.

**Comment by Jalle19** [comment]
Do you by any chance have "Prevent EPG updates during playback" enabled in Kodi's TV settings? That could prevent updates from coming through if you leave a channel playing.

**Comment by phunkyfish** [comment]
I'll try this for a few days and see does it fix the issue.

R.

**Comment by phunkyfish** [comment]
I think I know the problem. The buffer file for time shift fills up the storage. Once this is full you can't write anymore guide data.

Does that make sense?

R.

**Comment by Jalle19** [comment]
Closing this in favor of https://github.com/kodi-pvr/pvr.vbox/issues/51
