### ISSUE TITLE
Genre Colours

### ISSUE THREAD

**Issue by mriksman** [kodi-pvr/pvr.vbox#186]
Excited to see Kodi v17 hit the Google Play store, and my TVs have updated. VBox PVR Client shows 3.6.7, so the category-genre mapping should be taking place. Indeed, I can see genres like 'Soap, Melodrama' and 'Antiques, Collectibles'.

But they aren't coloured like I was expecting them to be... Any idea why? Have you got genre colours working OK on your end?

**Comment by mriksman** [comment]
#146 #130

**Comment by mriksman** [comment]
Where should the category_to_genre_types.xml file be on an Android TV? I can't find it...

**Comment by mriksman** [comment]
In the guide, I can see; 
Genre Sitcom
or
Genre Adventure
as I look at the details of each show. Which must mean the mapping has taken place....? So I guess my question is; where is the colours? The default Estuary and Artic Zephyr show no colours...

**Comment by mriksman** [comment]
Hah. I had to Clear Data and Disable/Enable for it to come good. Genre names have changed (must be the mapping ACTUALLY working now), and colors are visible.

**Comment by Jalle19** [comment]
Interesting, but glad you solved it!
