### ISSUE TITLE
I need Android and iOS addon. Please give me the instruction for iOS and Android

### ISSUE THREAD

**Issue by songxunzhao** [kodi-pvr/pvr.vbox#202]
Hi. pvr.vbox developers.
I'm very interesting in pvr.vbox KODI Addon.
Would you like give me the iOS and Android build instructions for pvr.vbox KODI addon?
Thanks&Regards.

**Comment by Jalle19** [comment]
I honestly have no idea how to build for either of those platforms. If you install Kodi normally you should have all PVR addons included out of the box, including this one.

If you insist you should ask on the forums instead, this is the bug tracker.

**Comment by MartijnKaijser** [comment]
You might need to enable the addon first understanding my addons

**Comment by Jalle19** [comment]
Indeed, you go to My addons and enable the one you want to use.

**Comment by songxunzhao** [comment]
What I want to know is not the kodi addon using method
I want to know how to make the pvr.vbox kodi addon for Android/iOS using this git source.
Thanks.

**Comment by Jalle19** [comment]
Like I said, ask on the forums, someone probably knows.
