### ISSUE TITLE
Plugin crashing Kodi in Android TV 8.0 Oreo

### ISSUE THREAD

**Issue by dannyspanish** [kodi-pvr/pvr.vbox#208]
Hi, 

I upgraded my Nvidia Shield TV the other night to the latest experience (7.0) which upgrades the OS to Oreo. Unfortunately, your Kodi plugin doesn't work on this android version, I've tried using version 17.6 and 18.0 Alpha 1 but enabling the PVR client forces the app to close. I have completely uninstalled and then reinstalled Kodi but this hasn't helped.

I have attached my Kodi debug log which will hopefully help, let me know if you need me to do anything else.
[kodi.log](https://github.com/kodi-pvr/pvr.vbox/files/2042501/kodi.log)

**Comment by dannyspanish** [comment]
Just wanted to add that I've also tried this on my Nexus Player running 8.1 and as soon as I enable the addon Kodi crashes. I've also tried other Kodi forks and the same thing happens. Without your addon I'm struggling to find a reliable way to create series recordings, perhaps the Vbox isn't the right device for me.

**Comment by mathiasslawik** [comment]
Hi,

I have the same issue as @dannyspanish. After updating my Shield TV to Oreo Kodi crashes immediately after loading the addon. I've also tried 18.0 Alpha 2 but to no avail.

Is there any progress on this issue?

If there is anything I can do to help, just tell me.

Best regards,
Mathias

**Comment by relipo** [comment]
@mathiasslawik @dannyspanish You can try tomorrow's nightly.
If you do, please let me know how this fix works for you guys.

**Comment by mathiasslawik** [comment]
Hello @relipo,

thank you very much - the plugin is working again! I've just installed Kodi 18.0-ALPHA3 Git:20180705-6935152 on the Shield TV and after a quick test everything seems to be working fine.

Best regards,
Mathias

**Comment by relipo** [comment]
#212 I also added this fix to the Krypton version, which should be available as an update to the add-on in the Krypton version, when a release is issued.

@MartijnKaijser I see you've issued the 3.6.10 release. This bug is critical for Android 8.0 users (Android-TV or not), since it crashes their entire Kodi app, whenever it tries to enable the add-on (also when loading the app). 
Question is: can you issue another release for the Krypton branch, for the sake of those users?
Thanks a lot

**Comment by relipo** [comment]
@mathiasslawik Great, enjoy

**Comment by Jalle19** [comment]
Closing this since AFAICT the issue was resolved a long time ago
