### ISSUE TITLE
Rewind live tv not working.

### ISSUE THREAD

**Issue by dhallam56** [kodi-pvr/pvr.vbox#216]
Pause live tv option is working and record is working. But on the latest Kodi 18 you cannot rewind or fast forward anymore via the addon. The time shift option is on within the addon settings.

Cheers

**Comment by JIBEST** [comment]
I have the same issue as the OP since upgrading to Leia

**Comment by henchrm** [comment]
Same issue for me since upgrading to Kodi 18.

**Comment by phunkyfish** [comment]
This will probably need the GetStreamTimes API implemented. If I can get hold of a vbox I can probably implement this for you.

What happens when you try and skip forward and back with a recording?

**Comment by phunkyfish** [comment]
What platform are you running?

**Comment by dhallam56** [comment]
I’m running kodi on nvidia shield device

**Comment by phunkyfish** [comment]
If I give you a test build can you try it to see if it works? You are running Leia I assume?

**Comment by phunkyfish** [comment]
Arm7: https://jenkins.kodi.tv/job/kodi-pvr/job/pvr.vbox/job/PR-224/2/artifact/cmake/addons/build/zips/pvr.vbox+android-armv7/pvr.vbox-4.5.0.zip

Arch64: https://jenkins.kodi.tv/job/kodi-pvr/job/pvr.vbox/job/PR-224/2/artifact/cmake/addons/build/zips/pvr.vbox+android-aarch64/pvr.vbox-4.5.0.zip

Not sure which you need for the shield.

**Comment by henchrm** [comment]
I'm running kodi 18.4 on Windows 10 (vbox pvr addon 4.4.8)
Recordings work fine
Timeshift 'works' (pause works) - but there are no fwd/rwd buttons, and no timeline to click. (left/right cursor keys also do nothing).
Looks like this has been raised on kodi support too....
https://forum.kodi.tv/showthread.php?tid=341072
and here...
https://forum.kodi.tv/showthread.php?tid=340906   
(dhallam)

Cheers.

**Comment by phunkyfish** [comment]
Ok here is a 64bit build to test with for Win10: https://jenkins.kodi.tv/job/kodi-pvr/job/pvr.vbox/job/PR-224/2/artifact/cmake/addons/build/zips/pvr.vbox+windows-x86_64/pvr.vbox-4.5.0.zip

**Comment by dhallam56** [comment]
I’ve got one on 19 alpha1 as a test and one on 18.4 but can happily test on both ;-)

**Comment by phunkyfish** [comment]
Let's see if we can get it working on Leia first and then we can move to Matrix. I'm trying to do this blind without a vbox so it might take a little while to get it to work ;)

**Comment by henchrm** [comment]
Afraid its the same with 4.5.0....  I've retried recordings, and they don't quite work as I thought... (there are also no 'buttons' for fwd/rwd) but you can click the time line and then it says press left/right, and the cursor keys work for skipping.  This doesn't work on live tv.

**Comment by henchrm** [comment]
kudos for trying to do this without a box BTW!

**Comment by phunkyfish** [comment]
Ok, the fact that recordings don't work correctly makes sense. Let me see if I'm missing something.

**Comment by phunkyfish** [comment]
When this works you should have Go to start, stop, pause, go to end and a record button.

**Comment by henchrm** [comment]
Sorry, yep - recordings are working exactly the same as movies (apologies, I tend to only use keyboard controls).
Live TV, once paused is now showing the word time shift, and the timeline is showing with the line representing where you are in the current tv schedule for that program. The time shift text is correctly reporting how far behind you are, but the timeline does not have the little arrows that you would get in a recording, and there is no way to move within the time shift period.

Cheers.

**Comment by phunkyfish** [comment]
What happens when you press left or right while timeshifting? It should move forward and back in the timeline.

**Comment by phunkyfish** [comment]
Could you post some screenshots?

**Comment by phunkyfish** [comment]
Do you record to a network location? If so can you load that as a video source (i.e. not from TV menu) and see do recordings still play and seek correctly.

If you record to USB maybe copy some to video source location and see if they play and seek correctly.

**Comment by dhallam56** [comment]
My recordings work and seek backwards and forwards fine it’s just the live tv doesn’t go back and forward at all. I’m recording to a network location. Cheers for the help esp without a VBox.  Mabel contact their support for a unit. As they are releasing a new box with android TV so might b able to spare a unit esp if keeping the plugin alive.

Cheers

**Comment by phunkyfish** [comment]
Ok cool. But in kodi if you access your recordings on the network via videos (I.e. not using TV->Recordings) can you still seek correctly?

There is a difference between recording playback from the PVR menus and from regular kodi playback.

**Comment by phunkyfish** [comment]
Can you try this build, just download the one for your platform: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-224/3/artifacts

The mistake earlier was a simple one. Also, on recordings I implemented the same so the Ui will correctly show the in progress recordings (red dot in Recordings view) and when viewing them the duration will increase as you watch.

Assuming it all works.

**Comment by phunkyfish** [comment]
> Cheers for the help esp without a VBox. Mabel contact their support for a unit. As they are releasing a new box with android TV so might b able to spare a unit esp if keeping the plugin alive.

I had a vbox many years ago, but changed since. To be honest if I had one I'd just have to break my current system to run it so probably not worth it.

**Comment by dhallam56** [comment]
Yes seaking works fine for me either running from the TV Recordings section. And if i add it via UNC path to the video section Seaking back and forward works for me. Its just live tv doesent ;-)

**Comment by phunkyfish** [comment]
> Can you try this build, just download the one for your platform: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-224/3/artifacts
> 

Did you try the new build yet?

**Comment by henchrm** [comment]
Thank you so much, its working perfectly now in live TV!  Dare I ask what you are using now instead of vbox?

**Comment by phunkyfish** [comment]
Amazing!!!

An Enigma2 receiver (specifically a VU+ device), I maintain the pvr.vuplus addon for it. But the addon work with all Enigma2 devices.

Could you also test the changes with Matrix?

Here are the Matrix builds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-225/1/artifacts

**Comment by dhallam56** [comment]
> 
> 
> > Can you try this build, just download the one for your platform: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-224/3/artifacts
> 
> Did you try the new build yet?

Not yet will try later (kids bedtime LOL) but looks like henchrm states its working.

Will these new builds need a new repo adding? or will they be added to the Kodi built in addons?

cheers

**Comment by phunkyfish** [comment]
You should never need to add a repo for pvr addons. They should appear via the normal update mechanism for your platform once reviewed and merged.

**Comment by henchrm** [comment]
I didn't have Matrix, but have now installed... I think the plugin upgrade is working there too, but I'm struggling to keep this kodi build up and running to be totally sure ;)

**Comment by dhallam56** [comment]
Cheers thanks for all your time on this was only a niggling issue but you have gone above and beyond to get it resolved. 
Cheers (+ the wife will love rewinding her soap's again LOL)... not sure i will

**Comment by phunkyfish** [comment]
Very good 😉

One last test to do. Can you record something that is on now and then try and play a recording while it’s still recording? There should be a red dot in the recordings UI and the duration should count upwards as you watch it.

If that works too then I can request a review.

**Comment by henchrm** [comment]
Yep, that's exactly what happens... :)

**Comment by phunkyfish** [comment]
Perfect, then are good 😎

**Comment by phunkyfish** [comment]
Released
