### ISSUE TITLE
Build instructions for Linux / OS X

### ISSUE THREAD

**Issue by sunstealer** [kodi-pvr/pvr.vbox#67]
The build instructions for Windows give some clues but it would be very helpful to have instructions for the simplest way to build just the pvr.vbox addon in either Linux or OS X, including cross-compiling for different architectures

Thanks

**Comment by Jalle19** [comment]
Please see http://forum.kodi.tv/showthread.php?tid=219166, the build instructions in the README is mainly for developers (the process is slightly different depending on whether you just want to build the current release or if you want to do development).
