### ISSUE TITLE
radio channels stuttering

### ISSUE THREAD

**Issue by adamlaw2** [kodi-pvr/pvr.vbox#69]
The TV channels are fine but the radio channels are constantly breaking up / stuttering.  If I use IPTV Simple Client in Kodi the radio channels are fine.  Also they are fine with VLC,  so this is something specific to your plugin. Do you also experience this problem (I am based in the UK)? 

Many thanks
Adam

**Comment by adamlaw2** [comment]
For this issue you suggested the following fix:

"let Kodi play radio channels directly without using the streaming int"
https://github.com/kodi-pvr/pvr.vbox/commit/9ec3e61ab39128371d984561252278c41ac17fc6#diff-34f48ad91ac6c202ac60b0348ae90e30



I am sorry but I don't know how to implement this fix - what do I have to do with the posted code?  I am not a programmer so don't know what to do.  Is there a build I can download which already implements the fix to stop the radio channels from stuttering?

Many thanks 
Adam

**Comment by Jalle19** [comment]
Just download and install the latest Kodi nightly.

**Comment by adamlaw2** [comment]
Thanks for your quick reply.  I downloaded a recent Kodi nightly and the radio stuttering does seem to be fixed.  I know on the post for the fix you said:

"The trade-off is that radio channels can't be timeshifted"

I don't seem to have this problem as I can record and pause radio channels fine - what are you referring to?

**Comment by Jalle19** [comment]
You can pause them temporarily but not forever. Recording is a different thing, that works just like before.

**Comment by adamlaw2** [comment]
In that case do you think it is possible to get time shifting working and still fix the stuttering problem?

**Comment by Jalle19** [comment]
It's probably possible, I almost had a solution but I decided to add a quick fix so that we at least have something that works at all.

**Comment by adamlaw2** [comment]
okay many thanks.  It sounds like you are making good progress.
