### ISSUE TITLE
easily select recording day - feature request 

### ISSUE THREAD

**Issue by adamlaw2** [kodi-pvr/pvr.vbox#70]
I can't see an easy way to select the day when recording?  As an example if I wanted to record something next Thursday I have to spend a lot of time scrolling all the way through the guide.  Is there any way to implement this, similar to how easy it is to select the day on the vbox web interface?

**Comment by Jalle19** [comment]
At the moment it's not that easy, starting from Kodi v16 it should be easier though since there's a large improvement for timer scheduling coming up.

**Comment by Mhir** [comment]
I've found a way to fast forward 12 hours by pressing ctrl F or ctrl B
