### ISSUE TITLE
ability to create groups - feature request

### ISSUE THREAD

**Issue by adamlaw2** [kodi-pvr/pvr.vbox#71]
With IPTV simple client I am able to create new groups in the group manager, however with your add-on I don't see the ability to create new groups.? The group manager only shows hidden TV channels, Visible TV channels and All channels.  I wanted to make a group e.g. called news but I can't see how to do this with your add-on?

**Comment by Jalle19** [comment]
The group management is done by Kodi in this case, not by the addon. The "Add group" is "hidden" by default, I've pushed a fix for that here: https://github.com/xbmc/xbmc/pull/7327
