### ISSUE TITLE
Upload of channel_mapping.xml 

### ISSUE THREAD

**Issue by Mhir** [kodi-pvr/pvr.vbox#72]
At the moment editing the channel_mapping.xml can easily be done on PC, however when using Android or iOS this is not as easy.
I suggest to provide a way to upload the file created on the PC to iOS and Android devices

**Comment by Jalle19** [comment]
See http://kodi.wiki/view/Android_FAQ#Where_is_the_Userdata_folder

**Comment by Mhir** [comment]
Hi,
Yes I was aware of this http://kodi.wiki/view/Userdata_folder
However I wasn't not sure how you upload a file to the iOS user_data folder without jailbreaking the device.
Anyway I found this and going to check it later to see if it works - https://itunes.apple.com/en/app/fileexplorer-free/id510282524?mt=8

Thanks

**Comment by Jalle19** [comment]
I haven't used iOS for a very long time so I can't really recommend any file browser app. Please report back if that app doesn't work out, in the worst case scenario we could add an option where the user gets to specify the location of the mapping file manually.
