### ISSUE TITLE
External EPG matching case sensitive

### ISSUE THREAD

**Issue by Mhir** [kodi-pvr/pvr.vbox#73]
It seems that the automatic channel matching is case sensitive and does not match channels with identical names for example
vbox=movies4men | xmltv=Movies4Men
vbox=QUEST | xmltv=Quest
vbox=POP | xmltv=Pop

I've uploaded both the XMLTV and channel_matching files - https://goo.gl/flcJBD

**Comment by Jalle19** [comment]
I just realized I managed to introduce a bug in this part of the code, will push a new release shortly.
