### ISSUE TITLE
1.3.3 proxy error - RPi 1 B, OpenElec

### ISSUE THREAD

**Issue by sunstealer** [kodi-pvr/pvr.vbox#75]
Gave new build a try in case you somehow fixed bug #59 

Now doesn't get as far as parsing xmltv and doesn't work even if external xmltv switched off

These errors in kodi.log:

22:35:16 1359.628784 T:1792709696   ERROR: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Request failed: No external Media is inserted (error code: 10)
22:35:17 1360.345825 T:1646261312   ERROR: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Request failed: Proxy Error 4 (error code: 5)
22:35:42 1385.865723 T:1646261312   ERROR: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Request failed: Proxy Error 4 (error code: 5)

From the code I think the first error is expected but the other 2 not?

Tried with default .kodi with just TV enabled and pvr.vbox enabled and configured

Pretty sure config is correct as its the same as it was before when addon ran but crashed with external xmltv data.  Simple IPTV client pvr addon still works perfectly.

**Comment by Jalle19** [comment]
Can you tey rebooting your VBox? These errors are coming from it.

**Comment by sunstealer** [comment]
Thanks - that fixed it - addon loads now - any idea of cause? TV Gateway up and running for some time but functioning fine for all other clients - would be good to get some feedback from pvr.vbox on screen to alert to possible problem

**Comment by Jalle19** [comment]
The VBox has random issues with its API, there's not much I can do about that. You'd have to contact their support so they can fix any remaining issues. It seems to have gotten worse with the latest firmware version.

@Mhir maybe you can ask your guys to look into these proxy errors? I've had issues where commands can randomly fail, seemingly becauae of out of memory issues on the device.

**Comment by sunstealer** [comment]
Thanks - I will speak to them
