### ISSUE TITLE
1.3.3 fails to load external XMLTV - RPi 1 B, OpenElec

### ISSUE THREAD

**Issue by sunstealer** [kodi-pvr/pvr.vbox#76]
This is same type of xmltv file as I've used previously - in the past, the file loads and parses but crashes with long descriptions (ref #59)

but now it doesn't seem to parse at all - debug level log file doesn't seem to shed much light on the problem:

09:47:32 537.969666 T:1687155776    INFO: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Loading external guide data
09:47:36 541.756775 T:1687155776   ERROR: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Request failed: XML parsing failed: XML_ERROR_PARSING
09:47:36 541.756958 T:1687155776    INFO: AddOnLog: VBox TV Gateway PVR Client: pvr.vbox - Failed to retrieve external guide data

The xmltv file is stored on an nfs share but kodi can see it when I browse for it in the configure window of pvr.vbox addon.

**Comment by Jalle19** [comment]
Wrong button... Can you upload a new XMLTV file somewhere?

**Comment by sunstealer** [comment]
done - usual dropbox ;-)

**Comment by Jalle19** [comment]
It could be that we're still dealing with the same issue, it's just that I improved the exception handling around this area of the code so the addon doesn't crash if there's something wrong with loading the external guide data file. I'll try to reproduce with your new file once I get home.

**Comment by sunstealer** [comment]
ok - that makes sense - thank you

**Comment by Mhir** [comment]
I have the same issue on my RPi 2 and Windows. 
I think that the issue is with the channel_matching.xml file that is not updating
Once I have copied the file from a previous version it started to collect the EPG data

**Comment by sunstealer** [comment]
ah ok - I will check that - I assumed it would keep the existing channel_matching.xml file - thanks

**Comment by Jalle19** [comment]
Try renaming the channel map file temporarily in case something's wrong with it.

**Comment by Jalle19** [comment]
Actually with the current code the external XMLTV data will not be used at all if the channel map file cannot be read, maybe I should change that.

**Comment by sunstealer** [comment]
@Mhir - thanks for the suggestion but I'm not sure what I should expect to find?  I went into the pvr.vbox folder and found channel_mappings.xml - it's the file that I set up ages ago and it's in the right place I think - I'm assuming the file is still meant to be in ~/.kodi/userdata/addon_data/pvr.vbox?

If so, then I have no clue what I'm looking for as I can't see anything wrong with the contents - they are still correct translations of the vbox channel name to the xmltv channel name as far as I can see - has something changed in the way this file should be formatted?

@Jalle19 - I tried renaming the file - it didn't do anything differently because, of course, the xmltv file wasn't loading before - and now it still isn't - the same xml parsing error is in the log.

**Comment by Jalle19** [comment]
@sunstealer so even after you renamed the file it didn't get recreated again the next time you started Kodi? That would indicate that it's the main external guide file that doesn't parse correctly, which is why it doesn't even bother loading the mapping file.

**Comment by sunstealer** [comment]
@Jalle19 - that's right - there was no new channel_mappings.xml file - so if I understand you correctly, this is an indication that your initial hunch was right i.e. we're back to the same problem at #59 but your error handling is better - or am I confused?

**Comment by Jalle19** [comment]
Yes, that's what I meant.

**Comment by sunstealer** [comment]
ok - thanks - did you have a chance to try the new xmltv.xml file or are we back to square 1 really? I'm slightly depressed that I can't get your addon to work on my RPi 1 with an external xmltv file - I was defeated by the compile instructions you pointed me at, unfortunately, as I feel I could probably pinpoint the problem if I could compile my own versions of your code

**Comment by Jalle19** [comment]
Sorry, haven't had time yet.

**Comment by sunstealer** [comment]
@Jalle19 - We were both thinking that maybe this was the same problem as #59 but actually I think it's probably something different because, as @Mhir found, it is possible to get the external xmltv.xml file to parse as long as it's not on a network share on the previous build (1.3.2) of pvr.vbox.  Even with the local xmltv.xml file, 1.3.3 doesn't parse the file properly.
