### ISSUE TITLE
No timeout for failed channel request

### ISSUE THREAD

**Issue by Mhir** [kodi-pvr/pvr.vbox#79]
pvr.vbox 1.3.4 on Mac OS
When zapping to a TV channel while the VBox lost RF connection. 
The add-on keeps trying (Waiting...) to access the channel and hangs Kodi, the only way to recover is forced quitting Kodi.

**Comment by Jalle19** [comment]
I can't test this at the moment because my VBox is in a remote location. It could be a generic issue in Kodi, I've heard of others who've had similar issues.

**Comment by Jalle19** [comment]
@Mhir on a second thought I think the VBox should close the connection if it determines that it has no signal. This would probably fix this issue.

**Comment by Mhir** [comment]
This could pose an issue when the signal is lost for a short while, the VBox is designed to try and resume the stream once the signal is back, if it will close the connection it will not try to resume.

**Comment by Jalle19** [comment]
Could you perhaps close the connection only after a certain period of time, like 10 seconds or so?

**Comment by Jalle19** [comment]
This does not seem to be a problem in Kodi Krypton anymore. If you select a channel which will never start playing (e.g. an encrypted channel that won't open) Kodi will no longer display "Working...", it will still allow you to switch to another channel.
