### ISSUE TITLE
Cannot add manual timer

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.vbox#89]
Adding a manual timer using the "Add timer" dialog seems to produce "returned an error: invalid parameters for this method", at least under some circumstances.

**Comment by brubri** [comment]
Hello Jalle19, yes this is exactly what I tried many times on 3 different machines with Kodi 15 and the vBox add-on:

It seems like the user tried adding a timer completely manually from the timer window. 

And I got the message error:

An unexpected error occured. Try again later or check the log for more information.

I sent VBox support the log file and will be happy to send it to you too if you can tell mere where as seems I cannot attach files here.

**Comment by falcon03** [comment]
Not sure if it is related, but after the update to version 2.50 of the VBox firmware there is no way to schedule a recording, neither manually nor from EPG. An erro message is always shown and the recording is not started...

**Comment by relipo** [comment]
Done in #144
