### ISSUE TITLE
Kodi on amazon fire tv freezes all the time when this plugin is active when left alone for a few hours

### ISSUE THREAD

**Issue by purplepenguinmedia** [kodi-pvr/pvr.vbox#93]
any help i can give or logs let me know.

**Comment by Jalle19** [comment]
Can you enable debug logging and pastebin a log where the freezes happen?

**Comment by purplepenguinmedia** [comment]
Will do this evening for you.

**Comment by purplepenguinmedia** [comment]
Ok problem, when it crashes and i reboot and upload logs.
http://xbmclogs.com/pminkvirl

They are only for the time after the reboot, how do i get them for the crash point?

**Comment by Jalle19** [comment]
There should be another log named kodi.log.old which is always the previous log. If something crashes then Kodi should also generate a separate crash log, check the wiki for how to find it on Android (I don't know).

**Comment by Jalle19** [comment]
You'll also have to enable debug logging in Kodi, otherwise the log won't tell me much.
