### ISSUE TITLE
Buffering on Minix 8

### ISSUE THREAD

**Issue by Mhir** [kodi-pvr/pvr.vbox#97]
Hi @Jalle19
The add-on starts to buffer after about 2 hours of watching, no other player (VBox apps, or browser) shows any similar issues at the same time and reception is good
Log file is available in this link - http://xbmclogs.com/pbd841jyp

hope that you can help
Thanks

**Comment by Jalle19** [comment]
I have a feeling it's the timeshift file that grows too large, it currently grows forever until playback is stopped or the channel is switched. What's the amount of storage on this device?

**Comment by Jalle19** [comment]
@Mhir is this still an issue with the latest Kodi beta?

**Comment by Jalle19** [comment]
Please try again with the latest version of Kodi.
