### ISSUE TITLE
Minix 8, changing channel after a while freeze the kodi

### ISSUE THREAD

**Issue by teisner** [kodi-pvr/pvr.vbox#99]
When open the live tv, and choose any channel, I can watch it, and even change to other channel,
but if I'm staying in one channel for a while (for example..10-15 min..), when I click on stop
and choose another channel, I got the 'please wait' circle...and nothing happen..
The only way to get out of it, is to force close of Kodi.

**Comment by Jalle19** [comment]
Can you post a debug log of when this happens?

**Comment by teisner** [comment]
sure/ will upload soon

**Comment by teisner** [comment]
I uploaded the log...
http://xbmclogs.com/pnhthuf3a
please note I'm not sure if this the right one, as the kodi hangs, and I have to force shut down of kodi, and reopen it, so I don't know if the log is of the crash one, or the new running ...

Please let me know. 

Tomer

**Comment by teisner** [comment]
ok, Please ignore the previous msg.
I managed to fetch the right log, with the bug (on the bottom of the log)
you can find it here : http://xbmclogs.com/p5k04y8tp

Thanks,
TOmer

**Comment by Jalle19** [comment]
Can't tell anything from the log. Does this always happen? Do you have timeshifting enabled?

**Comment by teisner** [comment]
no timeshifting. in addition, I found out its happen always when I'm using the Kodi for a while, and than, open the LiveTV to watch channel...and I have this issue only with this addon. other LiveTV seems to work just fine.
